# -*- coding: utf-8 -*-
"""data_science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tvklO2ysTewpwDo_o_SmWSDCu_fXM3H
"""

import pandas as pd


regions = ["Mondstadt","Inazuma","Liyue","Sumero","Fontaine", "Natlan","Snezhnaya"]

df = pd.read_csv("genshin_characters_v1.csv")
# df.sample(10)
# df.columns
# df.info()


def characters_per_region(region):
  region_cont = 0

  for i in range(94):
    result = df.at[i, 'region']
    if result == region:
      print(df.at[i, 'character_name'])
      region_cont += 1

  print(f"Existem {region_cont} personagens de {region}.")

def traduzir_arma(arma):
  if arma.lower() == "espada":
    return "Sword"
  elif arma.lower() == "lança" or arma.lower() == "lanca":
    return "Polearm"
  elif arma.lower() == "arco":
    return "Bow"
  elif arma.lower() == "catalisador":
    return "Catalyst"
  elif arma.lower() == "espadão" or arma.lower() == "espadao":
    return "Claymore"
  else:
    return arma.capitalize()


def star_rating():
  four_stars = 0
  five_stars = 0
  for i in range(94):
    result = df.at[i, 'star_rarity']
    if result == 4:
      four_stars += 1
    else:
      # print(df.at[i, 'character_name'])
      five_stars += 1

  print(f"Existem {four_stars} personagens com 4 estrelas.")
  print(f"Existem {five_stars} personagens com 5 estrelas.")

def check_vision(vision):
  for i in range(94):
    result = df.at[i, 'vision']
    if result == vision.capitalize():
      print(df.at[i, 'character_name'])


def check_weapon(weapon):
  for i in range(94):
    result = df.at[i, 'weapon_type']
    if result == weapon.capitalize():
      print(df.at[i, 'character_name'])



def check_weapon_vision():
  user_element = input("Digite o elemento: ")
  user_weapon = input("Digite a arma: ")


  for i in range(94):
    result = df.at[i, 'vision']
    result2 = df.at[i, 'weapon_type']
    if result == user_element.capitalize() and result2 == user_weapon.capitalize():
      print(df.at[i, 'character_name'])




program = True

while program:
  print("\nMenu:")
  print("1 - Listar personagens por região")
  print("2 - Contar personagens com 4 ou 5 estrelas")
  print("3 - Verificar personagens com determinada arma e visão")
  print("4 - Verificar personagens com determinada arma")
  print("5 - Verificar personagens com determinada visão")
  print("6 - Sair")

  choice = int(input("Digite a opção: "))

  if choice == 1:
    region = input("Digite a região: ")
    characters_per_region(region.capitalize())
  elif choice == 2:
    star_rating()
  elif choice == 3:
    check_weapon_vision()
  elif choice == 4:
    check_weapon(traduzir_arma(input("Digite a arma: ")))
  elif choice == 5:
    check_vision(input("Digite a visão: "))
  elif choice == 6:
    program = False
    print("Programa encerrado.")
  else:
    print("Opção inválida.")